/**
 * Financial statements as editorial tables: one row per standardized line item, periods
 * as columns (oldest → newest), YoY growth under each figure and a trend sparkline.
 */
import { Fragment, useMemo } from "react";
import { InfoTip, Panel, SegmentedControl, Sparkline, Toggle, useTabParam } from "../../components";
import { fmtNum, fmtPct, signClass } from "../../lib/format";
import { INFO } from "./info";
import { periodLabel, useStatements } from "./shared";
import type { Period, StatementTable, Statements } from "./types";

/** Subtotals rendered in bold with a rule above. */
const KEY_ROWS = new Set(["revenue", "gross_profit", "operating_income", "net_income", "total_assets", "total_liabilities", "equity", "cfo", "fcf"]);
/** Items that are outflows and conventionally shown in parentheses when positive. */
const OUTFLOWS = new Set(["cost_of_revenue", "sga", "rnd", "interest_expense", "income_tax", "capex", "dividends_paid", "buybacks", "d_and_a"]);

const SECTIONS: { key: "income_statement" | "balance_sheet" | "cash_flow"; title: string; subtitle: string; info: string }[] = [
  { key: "income_statement", title: "Income statement", subtitle: "How revenue becomes profit: costs, operating income, interest, tax and earnings per share.", info: "Flows over each period. Cost lines are shown in parentheses because they reduce profit." },
  { key: "balance_sheet", title: "Balance sheet", subtitle: "What the company owns and owes at each period end, and the owners' residual claim.", info: "Stocks measured at the period end. Total debt is long-term plus short-term borrowings as reported." },
  { key: "cash_flow", title: "Cash flow", subtitle: "Cash actually generated by operations and where it went: investment, dividends and buybacks.", info: "Free cash flow here is cash from operations minus capital expenditures (levered FCF; the DCF adds back after-tax interest)." },
];

const PERIODS: { value: Period; label: string; title: string }[] = [
  { value: "annual", label: "Annual", title: "Fiscal years (10-K)" },
  { value: "quarterly", label: "Quarterly", title: "Fiscal quarters (10-Q; Q4 derived as FY − 9M)" },
  { value: "ttm", label: "TTM", title: "Rolling trailing twelve months, one column per quarter end" },
];

export function StatementsTab({ ticker, compact }: { ticker: string; compact?: boolean }) {
  const [period, setPeriod] = useTabParam<Period>("period", "annual");
  const [yoyParam, setYoy] = useTabParam<"1" | "0">("yoy", "1");
  const showYoy = yoyParam === "1";
  const q = useStatements(ticker, period, period === "annual" ? 10 : 12);

  const controls = (
    <>
      <SegmentedControl size="sm" ariaLabel="Statement frequency" options={PERIODS} value={period} onChange={setPeriod} />
      <Toggle label="YoY growth" checked={showYoy} onChange={(v) => setYoy(v ? "1" : "0")} />
    </>
  );

  if (q.isError || q.isLoading)
    return <Panel title="Financial statements" subtitle="Income statement, balance sheet and cash flow from SEC XBRL filings." info={INFO.statements} query={q} compact={compact} actions={controls} skeletonHeight={420} />;

  const d = q.data!;
  return (
    <div className="stack-lg">
      <div className="co-toolbar">
        <div className="subtle small">
          USD millions except per-share figures; diluted shares in millions. {period === "ttm" && <><InfoTip info={INFO.ttm} size={12} /> TTM = sum of four consecutive quarters.</>}
          {showYoy && <> Small figures under each value are growth vs one year earlier <InfoTip info={INFO.yoy} size={12} />.</>}
        </div>
        <div className="row">{controls}</div>
      </div>
      {SECTIONS.map((s, i) => (
        <Panel<Statements>
          key={s.key}
          title={s.title}
          subtitle={s.subtitle}
          info={{ ...INFO.statements, title: s.title, text: `${s.info} ${INFO.statements.text}` }}
          query={q}
          flush
          notes={i === SECTIONS.length - 1 ? undefined : []}
          provenance={i === SECTIONS.length - 1 ? undefined : []}
        >
          {() => <FinTable table={d[s.key]} period={d.period} showYoy={showYoy} />}
        </Panel>
      ))}
    </div>
  );
}

function scaleOf(item: string): { div: number; digits: number; unit: string } {
  if (item === "eps_diluted") return { div: 1, digits: 2, unit: "$" };
  return { div: 1e6, digits: 0, unit: "" };
}

function fmtCell(v: number | null, item: string): string {
  if (v == null || !Number.isFinite(v)) return "—";
  const { div, digits } = scaleOf(item);
  const x = v / div;
  // Tiny companies: keep a decimal when the figure would otherwise round to 0.
  const dg = Math.abs(x) < 10 && div > 1 ? 1 : digits;
  const s = fmtNum(Math.abs(x), dg);
  if (OUTFLOWS.has(item) && x > 0) return `(${s})`;
  return x < 0 ? `−${s}` : s;
}

function FinTable({ table, period, showYoy }: { table: StatementTable; period: Period; showYoy: boolean }) {
  const rows = useMemo(() => table.rows.filter((r) => r.available), [table]);
  const missing = table.rows.filter((r) => !r.available).map((r) => r.label);
  const n = table.periods.length;
  return (
    <div className="co-fin-wrap">
      <table className="co-fin">
        <thead>
          <tr>
            <th className="co-fin-item">Line item</th>
            <th className="co-fin-spark" aria-label="Trend">
              Trend
            </th>
            {table.periods.map((p, j) => (
              <th key={p} className={`num ${j === n - 1 ? "co-fin-latest" : ""}`} title={p}>
                {periodLabel(p, period)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <Fragment key={r.item}>
              <tr className={KEY_ROWS.has(r.item) ? "co-fin-key" : ""}>
                <th scope="row" className="co-fin-item">
                  {r.label}
                </th>
                <td className="co-fin-spark">
                  <Sparkline values={r.values} width={72} height={22} color={OUTFLOWS.has(r.item) ? "var(--text-3)" : undefined} />
                </td>
                {r.values.map((v, j) => {
                  const g = r.yoy?.[j] ?? null;
                  const bad = OUTFLOWS.has(r.item);
                  return (
                    <td key={j} className={`num ${j === n - 1 ? "co-fin-latest" : ""}`}>
                      <div>{fmtCell(v, r.item)}</div>
                      {showYoy && <div className={`co-fin-yoy ${g == null ? "subtle" : signClass(g, bad)}`}>{g == null ? "" : `${g > 0 ? "+" : ""}${fmtPct(g, 1)}`}</div>}
                    </td>
                  );
                })}
              </tr>
            </Fragment>
          ))}
        </tbody>
      </table>
      {missing.length > 0 && <div className="co-fin-missing subtle small">Not reported in the filings for these periods: {missing.join(", ")}.</div>}
    </div>
  );
}
