/**
 * Every model in OhCamel Quant as structured data: plain-English summary, key formulas
 * (KaTeX), assumptions & caveats, where it appears in the app, and references (keys into
 * ./references.ts). Authored from the docstrings in quant/src/ohcamel_quant/{risk,
 * portfolio,factors,backtest,options,macro,fundamentals,data}/ — keep them in sync.
 */
const T = String.raw;

export type SectionId = "risk" | "portfolio" | "factors" | "backtest" | "options" | "macro" | "fundamentals" | "data";

export interface Model {
  id: string;
  name: string;
  section: SectionId;
  summary: string;
  formulas: { tex: string; caption?: string }[];
  assumptions: string[];
  appears: { label: string; to: string }[];
  refs: string[];
  keywords?: string;
}

export const SECTIONS: { id: SectionId; title: string; blurb: string }[] = [
  { id: "risk", title: "Risk", blurb: "How much could the portfolio lose, how often, and where does that risk come from? Value-at-Risk and Expected Shortfall under seven models, their out-of-sample backtests, risk decomposition and stress tests." },
  { id: "portfolio", title: "Portfolio construction", blurb: "Turning return histories into weights: covariance estimation, expected-return models, optimizers from Markowitz to hierarchical risk parity, and honest walk-forward comparison." },
  { id: "factors", title: "Factors & performance", blurb: "Describing a return series and explaining it: tear-sheet statistics, the statistical uncertainty of a Sharpe ratio, and Fama–French factor regressions with robust standard errors." },
  { id: "backtest", title: "Backtesting & validation", blurb: "A causal backtester for published strategies, and the diagnostics that tell a real edge from a lucky or overfitted one." },
  { id: "options", title: "Options & volatility", blurb: "Pricing and greeks, implied volatility, smiles and surfaces fitted without arbitrage, risk-neutral densities, realized-volatility estimators and the volatility risk premium." },
  { id: "macro", title: "Rates & macro", blurb: "The Treasury curve (bootstrapped and fitted), its principal components, bond risk measures, recession probabilities, market regimes and policy rules." },
  { id: "fundamentals", title: "Fundamentals", blurb: "From SEC filings to valuation: standardized statements, ratios, accounting-quality scores and a discounted-cash-flow model with a reverse DCF." },
  { id: "data", title: "Data & provenance", blurb: "The rules every number obeys: where it came from, when, and what happens when a source is missing." },
];

const PL_RISK = { label: "Portfolio Lab · Risk", to: "/portfolio?tab=risk" };
const PL_STRESS = { label: "Portfolio Lab · Stress", to: "/portfolio?tab=stress" };
const PL_FACTORS = { label: "Portfolio Lab · Factors", to: "/portfolio?tab=factors" };
const PL_OVERVIEW = { label: "Portfolio Lab · Overview", to: "/portfolio" };
const OPT = { label: "Optimizer", to: "/optimize" };
const OPT_FRONTIER = { label: "Optimizer · Frontier", to: "/optimize?tab=frontier" };
const OPT_COV = { label: "Optimizer · Covariance", to: "/optimize?tab=covariance" };
const OPT_VIEWS = { label: "Optimizer · Views", to: "/optimize?tab=views" };
const OPT_BT = { label: "Optimizer · Backtest vs 1/N", to: "/optimize?tab=backtest" };
const LAB = { label: "Strategy Lab", to: "/research" };
const LAB_SWEEP = { label: "Strategy Lab · Sweep & overfitting", to: "/research?tab=sweep" };
const LAB_WF = { label: "Strategy Lab · Walk-forward", to: "/research?tab=walkforward" };
const LAB_COSTS = { label: "Strategy Lab · Costs", to: "/research?tab=costs" };
const VOL_SURF = { label: "Volatility · Smile & surface", to: "/options?tab=surface" };
const VOL_DENS = { label: "Volatility · Density", to: "/options?tab=density" };
const VOL_REAL = { label: "Volatility · Realized", to: "/options?tab=realized" };
const VOL_CHAIN = { label: "Volatility · Chain & strategies", to: "/options?tab=chain" };
const VOL_CALC = { label: "Volatility · Calculator", to: "/options?tab=calculator" };
const MACRO = { label: "Rates & Macro", to: "/macro" };
const CO = (tab: string, label: string) => ({ label: `Company · ${label}`, to: `/company/AAPL?tab=${tab}` });
const TICKER = { label: "Ticker", to: "/ticker/SPY" };
const ENGINE = { label: "Live Engine", to: "/engine" };
const MARKETS = { label: "Markets", to: "/" };

export const MODELS: Model[] = [
  // =================================================================== RISK
  {
    id: "var-historical",
    name: "Historical-simulation VaR & ES",
    section: "risk",
    summary: "Rank the portfolio's actual past daily losses. VaR is the loss exceeded on only the worst (1 − α) share of days; Expected Shortfall is the average of those worst days. No distribution is assumed — history is the model.",
    formulas: [
      { tex: T`k = \lceil n(1-\alpha) \rceil,\quad \text{VaR}_\alpha = L_{(k)},\quad \text{ES}_\alpha = \frac{1}{k}\sum_{j=1}^{k} L_{(j)}`, caption: "L₍ⱼ₎ = j-th largest loss" },
      { tex: T`\text{ES}_\alpha = \mathbb{E}[L \mid L \ge \text{VaR}_\alpha]` },
    ],
    assumptions: ["The past window is representative of tomorrow; regimes absent from the window are invisible.", "Weights are held constant (daily rebalanced); multi-day horizons use overlapping compounded h-day returns.", "VaR and ES are positive loss fractions of equity; dollar figures multiply by notional."],
    appears: [PL_RISK, ENGINE],
    refs: ["jorion_2007", "acerbi_tasche_2002"],
    keywords: "value at risk expected shortfall cvar tail loss",
  },
  {
    id: "var-parametric",
    name: "Parametric VaR: Gaussian, Student-t and Cornish–Fisher",
    section: "risk",
    summary: "Fit a distribution to returns and read the tail from it. The normal model uses mean and volatility; Student-t adds fat tails with degrees of freedom fitted by maximum likelihood; Cornish–Fisher bends the normal quantile for skewness and kurtosis.",
    formulas: [
      { tex: T`\text{VaR} = -h\mu + \sqrt{h}\,\sigma z_\alpha,\qquad \text{ES} = -h\mu + \sqrt{h}\,\sigma\frac{\varphi(z_\alpha)}{1-\alpha}`, caption: "Gaussian (variance–covariance)" },
      { tex: T`\text{ES}^*_\nu = \frac{g_\nu(q)}{1-\alpha}\,\frac{\nu + q^2}{\nu-1}\sqrt{\tfrac{\nu-2}{\nu}},\quad q = t_\nu^{-1}(\alpha)`, caption: "unit-variance Student-t shortfall" },
      { tex: T`g = z + \tfrac{(z^2-1)S}{6} + \tfrac{(z^3-3z)K}{24} - \tfrac{(2z^3-5z)S^2}{36}`, caption: "Cornish–Fisher quantile (S skew, K excess kurtosis)" },
    ],
    assumptions: ["i.i.d. returns and square-root-of-time scaling for h > 1 days.", "Student-t variance is matched to the sample variance (location = sample mean).", "Cornish–Fisher is only valid when the expansion is monotone; the modified ES uses the Boudt–Peterson–Croux tail mean and is floored at VaR."],
    appears: [PL_RISK],
    refs: ["riskmetrics_1996", "jorion_2007", "mcneil_2015", "cornish_fisher_1937", "boudt_2008"],
    keywords: "normal gaussian student t modified var cornish fisher",
  },
  {
    id: "var-ewma",
    name: "EWMA volatility (RiskMetrics)",
    section: "risk",
    summary: "Volatility that remembers recent days more than old ones. Each day's variance forecast blends yesterday's forecast with yesterday's squared return, so risk estimates react quickly after a shock.",
    formulas: [{ tex: T`\sigma^2_{t+1} = \lambda\,\sigma^2_t + (1-\lambda)\,r_t^2,\quad \lambda = 0.94` }, { tex: T`\text{VaR} = \sqrt{h}\,\sigma_{t+1} z_\alpha` }],
    assumptions: ["Zero mean, conditionally normal returns.", "λ = 0.94 is the RiskMetrics daily decay (effective memory ≈ 1/(1−λ) ≈ 17 sessions)."],
    appears: [PL_RISK, ENGINE],
    refs: ["riskmetrics_1996"],
    keywords: "exponentially weighted moving average",
  },
  {
    id: "var-evt",
    name: "Extreme value theory (peaks over threshold)",
    section: "risk",
    summary: "Model only the tail. Losses beyond a high threshold (the 90th percentile) are fitted with a generalized Pareto distribution, which extrapolates to rare losses more credibly than a normal curve.",
    formulas: [
      { tex: T`G_{\xi,\beta}(y) = 1 - \left(1 + \tfrac{\xi y}{\beta}\right)^{-1/\xi}` },
      { tex: T`\text{VaR} = u + \tfrac{\beta}{\xi}\left[\left(\tfrac{n}{N_u}(1-\alpha)\right)^{-\xi} - 1\right],\quad \text{ES} = \tfrac{\text{VaR}}{1-\xi} + \tfrac{\beta - \xi u}{1-\xi}` },
    ],
    assumptions: ["Exceedances are i.i.d. above the threshold; ES is finite only for ξ < 1.", "Multi-day figures use square-root-of-time scaling (a stated caveat for heavy tails)."],
    appears: [PL_RISK],
    refs: ["mcneil_frey_2000", "mcneil_2015"],
    keywords: "evt gpd generalized pareto tail",
  },
  {
    id: "garch",
    name: "GARCH(1,1)-t, GJR-GARCH and filtered historical simulation",
    section: "risk",
    summary: "Volatility clusters: calm days follow calm days and storms follow storms. GARCH forecasts tomorrow's volatility from today's shock and today's volatility; GJR lets bad news raise volatility more than good news. Filtered historical simulation rescales past standardized shocks to today's forecast volatility.",
    formulas: [
      { tex: T`\sigma^2_t = \omega + (\alpha + \gamma\,\mathbb{1}[\varepsilon_{t-1}<0])\,\varepsilon^2_{t-1} + \beta\,\sigma^2_{t-1}` },
      { tex: T`\mathbb{E}_T\,\sigma^2_{T+k} = \bar\sigma^2 + P^{k-1}(\sigma^2_{T+1} - \bar\sigma^2),\quad P = \alpha + \tfrac{\gamma}{2} + \beta` },
      { tex: T`r^*_{T+1} = \mu + \sigma_{T+1} z_j,\quad z_j = \varepsilon_j/\sigma_j`, caption: "FHS scenarios" },
    ],
    assumptions: ["Standardized Student-t innovations with ν estimated jointly.", "h-day VaR uses the aggregated variance forecast; FHS bootstraps whole paths with a fixed seed for reproducibility."],
    appears: [PL_RISK],
    refs: ["bollerslev_1986", "glosten_1993", "barone_adesi_1999"],
    keywords: "conditional volatility gjr fhs",
  },
  {
    id: "var-backtest",
    name: "VaR & ES backtesting",
    section: "risk",
    summary: "Does the risk model deserve trust? Each model forecasts tomorrow using only past data, day after day; the tests then ask whether breaches happen as often as promised (Kupiec), independently of each other (Christoffersen, DQ), and whether ES matches the size of tail losses (Acerbi–Székely).",
    formulas: [
      { tex: T`LR_{POF} = -2\ln\!\left[(1-p)^{T-x}p^x\right] + 2\ln\!\left[(1-\tfrac{x}{T})^{T-x}(\tfrac{x}{T})^x\right] \sim \chi^2_1` },
      { tex: T`LR_{cc} = LR_{POF} + LR_{ind} \sim \chi^2_2` },
      { tex: T`Z_2 = \sum_t \frac{r_t I_t}{T p\,\text{ES}_t} + 1`, caption: "E[Z₂] = 0 under a correct ES" },
    ],
    assumptions: ["Rolling out-of-sample windows; parametric models refit every session, heavy ones every refit_every sessions with GARCH variances filtered daily.", "Basel traffic light zones come from the binomial CDF of the exception count (green < 95%, red ≥ 99.99%).", "Z₂ critical values from the paper are exact only for 97.5% ES and T = 250."],
    appears: [PL_RISK],
    refs: ["kupiec_1995", "christoffersen_1998", "bcbs_1996", "engle_manganelli_2004", "acerbi_szekely_2014", "fissler_ziegel_2016", "patton_2019"],
    keywords: "kupiec christoffersen traffic light dynamic quantile acerbi szekely fz0",
  },
  {
    id: "euler",
    name: "Risk decomposition (Euler allocation)",
    section: "risk",
    summary: "Splits total risk into additive pieces, one per position: each position's weight times how much the total would change if that weight grew a little. The pieces sum exactly to the total, so they answer “where is the risk?”.",
    formulas: [
      { tex: T`\rho(w) = \sum_i w_i \frac{\partial\rho}{\partial w_i}` },
      { tex: T`\text{marginal}_i = -h\mu_i + \sqrt{h}\,c\,\frac{(\Sigma w)_i}{\sigma_p}` },
      { tex: T`TE = \sqrt{a^\top \Sigma a},\quad a = [w; -1]`, caption: "ex-ante tracking error" },
    ],
    assumptions: ["The risk measure is positively homogeneous of degree 1.", "Historical ES components average the positions' P&L over the k worst portfolio days, and sum to ES exactly."],
    appears: [PL_RISK, ENGINE],
    refs: ["tasche_2000", "grinold_kahn_2000"],
    keywords: "component var marginal contribution tracking error beta",
  },
  {
    id: "stress",
    name: "Stress tests: historical replay and conditional stress",
    section: "risk",
    summary: "What would a past crisis do to today's portfolio? Each scenario replays the actual price path of every holding through a dated window (proxying unlisted names by beta). The conditional stress shocks a few assets and moves the rest by their expected response given the correlations.",
    formulas: [{ tex: T`\text{PnL}_t = \sum_i w_i R_i(t),\quad R_i(t) = \tfrac{P_i(t)}{P_i(\text{base})} - 1` }, { tex: T`\mathbb{E}[r_o \mid r_s = x] = \Sigma_{os}\Sigma_{ss}^{-1}x` }],
    assumptions: ["Buy-and-hold from the scenario's base close.", "A holding without prices over the window is proxied by β × benchmark and flagged; if no proxy exists the scenario is marked incomplete — nothing is invented.", "Conditional stress assumes joint normality with zero mean over the shock horizon."],
    appears: [PL_STRESS],
    refs: ["kupiec_1998"],
    keywords: "scenario gfc covid crisis shock",
  },

  // =================================================================== PORTFOLIO
  {
    id: "covariance",
    name: "Covariance estimation & shrinkage",
    section: "portfolio",
    summary: "Every optimizer needs a covariance matrix, and the sample estimate is noisy when assets are many and history short. Shrinkage pulls it towards a simple, stable target; random-matrix denoising replaces eigenvalues that are indistinguishable from noise.",
    formulas: [
      { tex: T`\hat\Sigma = \delta^* F + (1-\delta^*)S,\quad \delta^* = \max\!\left(0, \min\!\left(1, \tfrac{\kappa}{T}\right)\right)`, caption: "Ledoit–Wolf, constant-correlation target F" },
      { tex: T`\lambda_\pm = \sigma^2\left(1 \pm \sqrt{N/T}\right)^2`, caption: "Marčenko–Pastur noise band" },
    ],
    assumptions: ["Inputs are daily returns without gaps; outputs are annualized (× 252).", "EWMA uses zero mean and weights renormalized over the sample; OAS and Ledoit–Wolf identity shrink towards (tr S / N)·I."],
    appears: [OPT_COV, OPT],
    refs: ["ledoit_wolf_2004a", "ledoit_wolf_2004b", "chen_2010", "lopez_de_prado_2020", "laloux_1999", "riskmetrics_1996"],
    keywords: "ledoit wolf oas marcenko pastur denoise sample ewma",
  },
  {
    id: "expected-returns",
    name: "Expected returns: historical, Bayes–Stein, CAPM",
    section: "portfolio",
    summary: "Estimated means are the least reliable input in portfolio construction. Bayes–Stein shrinks each asset's historical mean towards a common grand mean; the CAPM replaces means with beta times the market premium.",
    formulas: [
      { tex: T`\mu_{BS} = (1-w)\hat\mu + w\,\mu_0\mathbf{1},\quad w = \frac{N+2}{(N+2) + T(\hat\mu - \mu_0\mathbf{1})^\top\Sigma^{-1}(\hat\mu - \mu_0\mathbf{1})}` },
      { tex: T`\mu_i = r_f + \beta_i\,(\mathbb{E}[r_b] - r_f)` },
    ],
    assumptions: ["Arithmetic means (× 252) are used in optimizers because portfolio means are linear in weights; the geometric figure is reported alongside.", "CAPM betas and the benchmark premium are estimated over the chosen window."],
    appears: [OPT],
    refs: ["jorion_1986", "sharpe_1964", "lintner_1965"],
    keywords: "james stein shrinkage capm equilibrium mean",
  },
  {
    id: "black-litterman",
    name: "Black–Litterman",
    section: "portfolio",
    summary: "Start from the returns the market implicitly expects (those that make current market weights optimal), then tilt them towards your own views in proportion to how confident you are. Produces sensible, diversified portfolios instead of extreme corner solutions.",
    formulas: [
      { tex: T`\pi = \delta\,\Sigma\,w_{mkt}` },
      { tex: T`\mu_{BL} = \pi + \tau\Sigma P^\top (P\tau\Sigma P^\top + \Omega)^{-1}(Q - P\pi)` },
    ],
    assumptions: ["Ω is set view-by-view from Idzorek's 0–100% confidence (100% reproduces the view exactly; 0% ignores it).", "Absolute views are total returns and enter Q as excess returns; relative views are spreads."],
    appears: [OPT_VIEWS],
    refs: ["black_litterman_1992", "he_litterman_1999", "idzorek_2005"],
    keywords: "views bayesian prior posterior idzorek",
  },
  {
    id: "mean-variance",
    name: "Mean–variance, minimum variance & the efficient frontier",
    section: "portfolio",
    summary: "Markowitz's idea: for any target return, hold the mix with the least variance. The minimum-variance portfolio ignores returns entirely; the tangency (max-Sharpe) portfolio is the best risk/return trade-off when you can also hold cash.",
    formulas: [
      { tex: T`\min_w\ w^\top\Sigma w \ \text{ s.t. } \mu^\top w \ge R,\ \mathbf{1}^\top w = 1,\ \ell \le w \le u` },
      { tex: T`\max_w\ \frac{\mu^\top w - r_f}{\sqrt{w^\top\Sigma w}}` },
    ],
    assumptions: ["Convex programs solved with SLSQP on exact gradients (max-Sharpe via the Cornuéjols–Tütüncü homogenization); leverage and turnover limits are linearized.", "Results are only as good as μ and Σ — see shrinkage and Black–Litterman."],
    appears: [OPT_FRONTIER, OPT],
    refs: ["markowitz_1952", "sharpe_1964"],
    keywords: "markowitz tangency gmv max sharpe frontier optimizer",
  },
  {
    id: "risk-parity",
    name: "Equal risk contribution & maximum diversification",
    section: "portfolio",
    summary: "Instead of forecasting returns, budget risk: every asset contributes the same share of portfolio volatility (risk parity), or the ratio of average asset volatility to portfolio volatility is maximized (most-diversified portfolio).",
    formulas: [
      { tex: T`RC_i = w_i\frac{(\Sigma w)_i}{\sqrt{w^\top\Sigma w}} = \frac{\sigma_p}{N}` },
      { tex: T`\min_{y>0}\ \tfrac12 y^\top\Sigma y - \sum_i b_i\ln y_i,\quad w = y/\mathbf{1}^\top y`, caption: "Spinu's convex formulation, damped Newton" },
      { tex: T`DR(w) = \frac{w^\top\sigma}{\sqrt{w^\top\Sigma w}}` },
    ],
    assumptions: ["Long-only.", "Relies on the covariance matrix only; no expected returns."],
    appears: [OPT],
    refs: ["maillard_2010", "spinu_2013", "choueifaty_2008"],
    keywords: "erc risk budgeting diversification ratio",
  },
  {
    id: "min-cvar",
    name: "Minimum CVaR",
    section: "portfolio",
    summary: "Choose weights that minimize the average loss on the worst days in history, solved exactly as a linear program over historical scenarios.",
    formulas: [{ tex: T`\min_{w,\zeta,u}\ \zeta + \frac{1}{(1-\alpha)S}\sum_s u_s\quad \text{s.t. } u_s \ge -r_s^\top w - \zeta,\ u_s \ge 0` }],
    assumptions: ["Scenarios are the estimation window's daily returns; at the optimum ζ is the VaR.", "Solved with HiGHS via scipy's linprog."],
    appears: [OPT],
    refs: ["rockafellar_uryasev_2000"],
    keywords: "cvar expected shortfall linear program",
  },
  {
    id: "hrp",
    name: "Hierarchical risk parity (HRP) & HERC",
    section: "portfolio",
    summary: "Group assets by how similarly they move (a clustering tree), reorder the covariance so similar assets sit together, then split capital top-down between clusters in inverse proportion to their variance. No matrix inversion, so it is robust to noisy estimates.",
    formulas: [{ tex: T`d_{ij} = \sqrt{\tfrac12(1-\rho_{ij})}` }, { tex: T`\alpha = 1 - \frac{V_L}{V_L + V_R},\quad w_L \leftarrow \alpha w_L,\ w_R \leftarrow (1-\alpha)w_R` }],
    assumptions: ["Single linkage on the paper's column distance by default.", "HERC follows the dendrogram's actual splits down to k clusters (largest gap in merge height when k is not given)."],
    appears: [OPT],
    refs: ["lopez_de_prado_2016", "raffinot_2018"],
    keywords: "clustering dendrogram herc tree",
  },
  {
    id: "naive",
    name: "1/N, inverse volatility & effective number of bets",
    section: "portfolio",
    summary: "The humble benchmarks that sophisticated optimizers often fail to beat out of sample, and a measure of how many independent bets a portfolio really makes.",
    formulas: [{ tex: T`w_i = \tfrac1N,\qquad w_i = \frac{\sigma_i^{-1}}{\sum_j \sigma_j^{-1}}` }, { tex: T`ENB = \exp\!\left(-\sum_k p_k\ln p_k\right),\quad p_k = \frac{\tilde w_k^2\lambda_k}{w^\top\Sigma w}` }],
    assumptions: ["ENB uses principal components of Σ (Meucci's entropy of variance shares), ranging from 1 to N."],
    appears: [OPT, OPT_BT],
    refs: ["demiguel_2009", "meucci_2009"],
    keywords: "equal weight inverse vol enb",
  },
  {
    id: "walkforward-opt",
    name: "Walk-forward comparison & Sharpe-difference tests",
    section: "portfolio",
    summary: "Evaluate every allocation method the way it would have been used: rebalance on a calendar using only data before the decision, let weights drift in between, pay trading costs, and compare out-of-sample Sharpe ratios with tests robust to fat tails and autocorrelation.",
    formulas: [
      { tex: T`\text{cost} = \kappa\sum_i\left|w_i^{new} - w_i^{drift}\right|,\ \kappa = \text{bps}/10^4` },
      { tex: T`z = \frac{SR_a - SR_b}{\sqrt{\theta}},\ \theta = \tfrac1T\left[2(1-\rho) + \tfrac12(SR_a^2 + SR_b^2 - 2SR_aSR_b\rho^2)\right]`, caption: "Jobson–Korkie with Memmel's correction" },
    ],
    assumptions: ["The estimation window strictly precedes each rebalance session.", "If a method has no solution (e.g. no tangency portfolio) the book moves to cash, and the event is counted.", "Ledoit–Wolf test uses a Bartlett HAC covariance with the Newey–West plug-in lag."],
    appears: [OPT_BT],
    refs: ["demiguel_2009", "memmel_2003", "ledoit_wolf_2008", "newey_west_1994"],
    keywords: "out of sample rebalance jobson korkie",
  },

  // =================================================================== FACTORS & PERFORMANCE
  {
    id: "performance",
    name: "Performance statistics",
    section: "factors",
    summary: "The standard tear sheet: compound growth, volatility, risk-adjusted returns and the depth and length of drawdowns — each computed exactly as defined in its source paper.",
    formulas: [
      { tex: T`\text{CAGR} = \left(\prod_t(1+r_t)\right)^{P/T} - 1,\qquad SR = \frac{\overline{r - r_f}}{\operatorname{sd}(r - r_f)}\sqrt{P}` },
      { tex: T`\text{Sortino} = \frac{\overline{r - \text{MAR}}\,P}{DD\sqrt P},\ DD = \sqrt{\overline{\min(r - \text{MAR}, 0)^2}}` },
      { tex: T`\Omega(L) = \frac{\sum\max(r_t - L, 0)}{\sum\max(L - r_t, 0)},\qquad \text{MDD} = \min_t\left(\frac{W_t}{\max_{s\le t}W_s} - 1\right)` },
    ],
    assumptions: ["Simple decimal returns, P = 252 sessions a year; arithmetic annualization for means and vols, geometric for CAGR.", "When no risk-free series is available it is treated as zero, and the panel says so."],
    appears: [PL_OVERVIEW, TICKER, LAB],
    refs: ["sharpe_1994", "sortino_price_1994", "keating_2002"],
    keywords: "sharpe sortino omega calmar drawdown cagr volatility ulcer",
  },
  {
    id: "sharpe-inference",
    name: "Sharpe-ratio inference: standard errors, PSR and MinTRL",
    section: "factors",
    summary: "A Sharpe ratio is an estimate with an error bar. Lo's standard errors, the Probabilistic Sharpe Ratio (the probability the true Sharpe beats a hurdle) and the Minimum Track Record Length (how much history you need to be confident) account for sample length, skewness and fat tails.",
    formulas: [
      { tex: T`\operatorname{Var}(\widehat{SR}) = \frac{1 + SR^2/2}{T}`, caption: "i.i.d. normal (Lo 2002)" },
      { tex: T`PSR(SR^*) = \Phi\!\left(\frac{(\widehat{SR} - SR^*)\sqrt{T-1}}{\sqrt{1 - \gamma_3\widehat{SR} + \frac{\gamma_4-1}{4}\widehat{SR}^2}}\right)` },
      { tex: T`\text{MinTRL} = 1 + \left(1 - \gamma_3 SR + \tfrac{\gamma_4-1}{4}SR^2\right)\left(\frac{z_{c}}{SR - SR^*}\right)^2` },
    ],
    assumptions: ["Sharpe ratios in these formulas are per period, not annualized; γ₄ is raw (non-excess) kurtosis.", "The GMM/HAC variant is robust to serial correlation."],
    appears: [PL_OVERVIEW, LAB],
    refs: ["lo_2002", "bailey_2012"],
    keywords: "psr probabilistic sharpe minimum track record",
  },
  {
    id: "factor-regression",
    name: "Fama–French & Carhart factor regressions",
    section: "factors",
    summary: "Explain a portfolio's excess return as exposure to known return drivers — the market, size, value, profitability, investment and momentum — plus an alpha that is left over. Standard errors are robust to heteroskedasticity and autocorrelation.",
    formulas: [
      { tex: T`r_t - r_{f,t} = a + \sum_k b_k f_{k,t} + e_t` },
      { tex: T`\hat V = (X^\top X)^{-1}\,[T\,S]\,(X^\top X)^{-1},\ S = \Gamma_0 + \sum_{j=1}^{L}\left(1 - \tfrac{j}{L+1}\right)(\Gamma_j + \Gamma_j^\top)`, caption: "Newey–West, L = ⌊4(T/100)^{2/9}⌋" },
    ],
    assumptions: ["Factors from Kenneth French's library (CAPM, FF3, Carhart 4, FF5, FF5 + momentum); when it is unreachable, tradable ETF long/short spreads can stand in (labelled as such).", "p-values use the normal limit."],
    appears: [PL_FACTORS],
    refs: ["fama_french_1993", "fama_french_2015", "carhart_1997", "newey_west_1987", "newey_west_1994", "huij_verbeek_2009"],
    keywords: "ff3 ff5 carhart momentum smb hml rmw cma alpha newey west hac",
  },
  {
    id: "attribution",
    name: "Factor risk decomposition & return attribution",
    section: "factors",
    summary: "Which factors created the return and which created the risk? Variance splits into each factor's Euler share plus residual; returns are attributed per day and linked over time so the pieces add up to the compounded total.",
    formulas: [
      { tex: T`\operatorname{Var}(y) = b^\top\Sigma_f b + \operatorname{Var}(e),\qquad c_k = b_k(\Sigma_f b)_k` },
      { tex: T`C_{i,T} = \sum_{t\le T} c_{i,t}\frac{k_t}{K_T},\ k_t = \frac{\ln(1+y_t)}{y_t},\ K_T = \frac{\ln(1+Y_T)}{Y_T}`, caption: "Cariño linking" },
    ],
    assumptions: ["Exact in-sample for OLS with an intercept; a factor's risk contribution can be negative (a hedge)."],
    appears: [PL_FACTORS],
    refs: ["carino_1999", "grinold_kahn_2000"],
    keywords: "carino linking contribution",
  },
  {
    id: "relative",
    name: "Benchmark-relative statistics",
    section: "factors",
    summary: "How a portfolio behaved against its benchmark: Jensen's alpha and beta, tracking error and information ratio, Treynor and M² (Sharpe restated in benchmark-volatility units), and up/down capture.",
    formulas: [{ tex: T`IR = \frac{\overline{r - b}\,P}{\operatorname{sd}(r-b)\sqrt P},\qquad M^2 = SR_p\,\sigma_b + \bar r_f P` }],
    assumptions: ["CAPM regression on excess returns with Newey–West t-statistics.", "Capture ratios use geometric means over up / down benchmark periods (daily and monthly)."],
    appears: [PL_OVERVIEW],
    refs: ["jensen_1968", "grinold_kahn_2000", "modigliani_1997"],
    keywords: "alpha beta tracking error information ratio treynor capture",
  },

  // =================================================================== BACKTEST
  {
    id: "bt-engine",
    name: "Causal target-weight backtester",
    section: "backtest",
    summary: "A strategy looks at data up to today's close and says what it wants to hold; the engine trades at a later close, lets positions drift, charges costs on what was actually traded, and audits the strategy for look-ahead by re-running it on truncated data.",
    formulas: [
      { tex: T`g_s = w^\top R_s + (1 - \mathbf{1}^\top w)\,r_{f,s} - \tfrac{b}{10^4\cdot252}\sum_i\max(-w_i,0)` },
      { tex: T`1 + \text{net}_s = (1+g_s)\left(1 - \tfrac{c}{10^4}\sum_i|w^*_i - \tilde w_i|\right)` },
    ],
    assumptions: ["Execution lag ≥ 1 session; a strategy that peeks raises LookAheadError.", "Optional volatility-target overlay uses an ex-ante EWMA or rolling covariance and a gross-leverage cap.", "Close-to-close fills at adjusted closes; no market impact beyond proportional costs."],
    appears: [LAB],
    refs: ["harvey_2018", "moreira_muir_2017"],
    keywords: "backtest lookahead costs execution lag volatility target",
  },
  {
    id: "strategies",
    name: "Strategy library",
    section: "backtest",
    summary: "Published strategies implemented causally with the papers' default parameters: time-series and cross-sectional momentum, dual momentum, the 10-month trend rule, volatility-managed and risk-parity portfolios, betting against beta, short-term reversal, and pairs trading by distance and cointegration.",
    formulas: [
      { tex: T`w_{i,t} = \frac{1}{S_t}\operatorname{sign}\!\left(r^{ex}_{i,t-L..t}\right)\frac{\sigma_{tgt}}{\sigma_{i,t}}`, caption: "time-series momentum" },
      { tex: T`f^\sigma_{t+1} = \frac{c}{\sigma^2_t}f_{t+1}`, caption: "volatility-managed, c re-estimated on an expanding window" },
    ],
    assumptions: ["Where a paper calibrates with full-sample information (e.g. Moreira–Muir's c, AFP's leverage), the real-time version is used instead.", "Universes are chosen by the user, so survivorship is the user's choice (see Limitations)."],
    appears: [LAB],
    refs: ["moskowitz_2012", "jegadeesh_titman_1993", "antonacci_2014", "faber_2007", "moreira_muir_2017", "asness_2012", "frazzini_pedersen_2014", "lehmann_1990", "gatev_2006", "engle_granger_1987"],
    keywords: "tsmom momentum trend sma bab betting against beta pairs reversal dual momentum",
  },
  {
    id: "pbo",
    name: "Probability of backtest overfitting (CSCV)",
    section: "backtest",
    summary: "If you tried many parameter settings and picked the best, how likely is it that your winner is below median out of sample? Split history into blocks, pick the in-sample winner on every half-split, and count how often it lands in the bottom half on the other half.",
    formulas: [{ tex: T`\lambda_c = \ln\frac{\omega_c}{1-\omega_c},\quad PBO = \frac{\#\{\lambda_c \le 0\}}{\binom{S}{S/2}}` }],
    assumptions: ["Trials are compared on identical sessions (the window where all are live).", "S contiguous equal blocks; leading rows dropped so S divides T."],
    appears: [LAB_SWEEP],
    refs: ["bailey_2017"],
    keywords: "overfitting cscv combinatorial",
  },
  {
    id: "dsr",
    name: "Deflated Sharpe ratio",
    section: "backtest",
    summary: "The best Sharpe ratio among many trials is inflated by luck. The deflated Sharpe ratio raises the hurdle to the Sharpe you would expect from the best of N worthless strategies, then asks how likely the observed one beats it.",
    formulas: [{ tex: T`SR_0 = \sqrt{V[SR_n]}\left((1-\gamma)\Phi^{-1}\!\left(1-\tfrac1N\right) + \gamma\,\Phi^{-1}\!\left(1 - \tfrac{1}{Ne}\right)\right),\quad DSR = PSR(SR_0)` }],
    assumptions: ["N = number of grid combinations; V[SR] is the cross-trial variance of per-period Sharpe ratios; γ is the Euler–Mascheroni constant."],
    appears: [LAB_SWEEP],
    refs: ["bailey_2014"],
    keywords: "deflated sharpe multiple testing selection bias",
  },
  {
    id: "bootstrap-spa",
    name: "Stationary bootstrap & Hansen's SPA test",
    section: "backtest",
    summary: "Resample realized history in random-length blocks (keeping its autocorrelation) to put a confidence interval on the Sharpe ratio, and test whether any strategy in the grid truly beats the benchmark after accounting for data snooping.",
    formulas: [{ tex: T`\text{block length} \sim \operatorname{Geom}(1/\bar b),\ \bar b = \text{Politis–White optimum}` }],
    assumptions: ["Bootstraps resample the real return series — they do not simulate markets.", "SPA reports lower / consistent / upper p-values; the consistent one is Hansen's recommendation."],
    appears: [LAB_SWEEP],
    refs: ["politis_romano_1994", "politis_white_2004", "hansen_2005"],
    keywords: "bootstrap confidence interval spa data snooping",
  },
  {
    id: "wfo-costs",
    name: "Walk-forward optimization & cost sensitivity",
    section: "backtest",
    summary: "Re-select parameters periodically using only past data and stitch the out-of-sample pieces together; then re-price the backtest at other trading-cost levels to find where the edge disappears.",
    formulas: [{ tex: T`1 + \text{net}_s(c) = (1 + g_s - \text{borrow}_s)(1 - c\cdot\text{turnover}_s)` }],
    assumptions: ["The in-sample block ends `lag` sessions before each switch, exactly like live execution.", "Turnover is invariant to the cost level, so re-pricing is exact; break-even costs are solved with Brent's method."],
    appears: [LAB_WF, LAB_COSTS],
    refs: ["pardo_2008"],
    keywords: "walk forward optimization break-even cost",
  },

  // =================================================================== OPTIONS
  {
    id: "bsm",
    name: "Black–Scholes–Merton / Black-76 & greeks",
    section: "options",
    summary: "The option-pricing formula and its sensitivities: delta (to the stock), gamma (delta's own change), vega (to volatility), theta (time decay) and rho (to rates), plus second-order vanna, volga and charm.",
    formulas: [
      { tex: T`V = D\left[\phi F N(\phi d_1) - \phi K N(\phi d_2)\right],\quad d_{1,2} = \frac{\ln(F/K) \pm \sigma^2T/2}{\sigma\sqrt T}` },
      { tex: T`\Delta = \phi e^{-qT}N(\phi d_1),\quad \Gamma = \frac{e^{-qT}n(d_1)}{S\sigma\sqrt T},\quad \mathcal V = Se^{-qT}n(d_1)\sqrt T` },
    ],
    assumptions: ["Lognormal prices, constant volatility and rates to expiry; continuous dividend yield q.", "Vega is per 1.00 of volatility; theta_day = theta / 365."],
    appears: [VOL_CALC, VOL_CHAIN],
    refs: ["merton_1973", "black_1976", "haug_2007"],
    keywords: "black scholes greeks delta gamma vega theta rho vanna volga charm",
  },
  {
    id: "implied-vol",
    name: "Implied volatility & implied forwards",
    section: "options",
    summary: "The volatility that makes the model price equal the market price. Forwards and discount factors come from put–call parity across strikes, so no external rate or dividend forecast is needed.",
    formulas: [{ tex: T`C(K) - P(K) = D(F - K)\ \Rightarrow\ D = -\beta,\ F = -\alpha/\beta,\ q = r - \tfrac{\ln(F/S)}{T}` }],
    assumptions: ["Inversion uses the out-of-the-money equivalent price (better conditioned), a Corrado–Miller start and safeguarded Newton on log price, then Brent.", "American-style options satisfy parity only as an inequality: the implied q absorbs early-exercise premium.", "T is ACT/365 from the quote instant to the AM or PM settlement instant."],
    appears: [VOL_CHAIN, VOL_SURF],
    refs: ["corrado_miller_1996", "stoll_1969", "cboe_vix"],
    keywords: "iv put call parity forward discount",
  },
  {
    id: "svi",
    name: "SVI smiles, surface & static-arbitrage checks",
    section: "options",
    summary: "A five-parameter curve for each expiry's smile in total variance, calibrated to quotes weighted by their bid–ask precision, then checked for butterfly (negative density) and calendar (variance falling with maturity) arbitrage.",
    formulas: [
      { tex: T`w(k) = a + b\left(\rho(k-m) + \sqrt{(k-m)^2 + \sigma^2}\right),\quad k = \ln(K/F)` },
      { tex: T`g(k) = \left(1 - \tfrac{k w'}{2w}\right)^2 - \tfrac{w'^2}{4}\left(\tfrac1w + \tfrac14\right) + \tfrac{w''}{2} \ge 0` },
    ],
    assumptions: ["Quasi-explicit calibration (exact inner QP, Nelder–Mead outer search).", "Between expiries total variance is interpolated linearly in T; no extrapolation."],
    appears: [VOL_SURF],
    refs: ["gatheral_2004", "zeliade_2009", "gatheral_jacquier_2014"],
    keywords: "svi smile surface butterfly calendar arbitrage",
  },
  {
    id: "smile-metrics",
    name: "Smile metrics & model-free implied variance",
    section: "options",
    summary: "Summaries traders quote: at-the-money vol, the 25-delta risk reversal (skew) and butterfly (wings), the smile's slope, a VIX-style model-free variance for any underlying and the implied move to expiry.",
    formulas: [
      { tex: T`RR_{25} = \sigma_{\Delta=+.25} - \sigma_{\Delta=-.25},\quad BF_{25} = \tfrac12(\sigma_{+.25} + \sigma_{-.25}) - \sigma_{ATM}` },
      { tex: T`\sigma^2 = \frac2T\sum_i\frac{\Delta K_i}{K_i^2}e^{RT}Q(K_i) - \frac1T\left(\frac{F}{K_0} - 1\right)^2` },
    ],
    assumptions: ["Forwards and discounting from parity (Cboe uses Treasury rates — stated).", "30-day constant maturity interpolates total variance between bracketing expiries."],
    appears: [VOL_SURF],
    refs: ["demeterfi_1999", "cboe_vix"],
    keywords: "vix risk reversal butterfly skew atm implied move",
  },
  {
    id: "density",
    name: "Risk-neutral density (Breeden–Litzenberger)",
    section: "options",
    summary: "The second derivative of call prices with respect to strike is the market's probability density for the price at expiry. It turns an option chain into implied probabilities, e.g. of a 10% fall.",
    formulas: [{ tex: T`q(K) = \frac1D\frac{\partial^2 C}{\partial K^2},\qquad P(S_T \le K) = 1 + \frac1D\frac{\partial C}{\partial K}` }],
    assumptions: ["Computed from the fitted smile, not raw quotes; the integral (≈ 1) and mean (≈ F) are reported as checks, never forced.", "These are risk-neutral probabilities, which embed risk premia — not real-world forecasts."],
    appears: [VOL_DENS],
    refs: ["breeden_litzenberger_1978", "ait_sahalia_lo_1998"],
    keywords: "risk neutral probability density",
  },
  {
    id: "realized-vol",
    name: "Realized volatility, the vol cone & the volatility risk premium",
    section: "options",
    summary: "How much the price actually moved, using closes or the full daily range (open, high, low, close); where today's value sits in its history at each horizon; and how implied volatility compares with what was later realized.",
    formulas: [
      { tex: T`\sigma^2_{P} = \frac{1}{4\ln2}\,\mathbb{E}\left[\ln(H/L)^2\right]`, caption: "Parkinson" },
      { tex: T`\sigma^2_{YZ} = V_O + kV_C + (1-k)V_{RS},\ k = \frac{0.34}{1.34 + \frac{n+1}{n-1}}`, caption: "Yang–Zhang" },
      { tex: T`VRP = \sigma_{implied} - \sigma_{realized}` },
    ],
    assumptions: ["Annualized with √252; windows are trailing.", "Cone windows overlap, so percentiles are not from independent samples."],
    appears: [VOL_REAL, TICKER],
    refs: ["parkinson_1980", "garman_klass_1980", "rogers_satchell_1991", "yang_zhang_2000", "burghardt_lane_1990", "carr_wu_2009"],
    keywords: "parkinson garman klass rogers satchell yang zhang cone vrp",
  },
  {
    id: "strategy-payoff",
    name: "Option strategy payoffs & probability of profit",
    section: "options",
    summary: "Multi-leg positions priced from real quotes: cost at mid and at the natural price, value across spot and time, breakevens, max profit/loss, net greeks and the probability of profit under the market's risk-neutral density.",
    formulas: [{ tex: T`\text{PoP} = \mathbb{Q}\left(\text{P\&L}(S_T) > 0\right)` }],
    assumptions: ["Sticky-strike: each leg keeps its own implied vol as time passes.", "PoP is risk-neutral and embeds the volatility risk premium."],
    appears: [VOL_CHAIN],
    refs: ["breeden_litzenberger_1978"],
    keywords: "payoff straddle spread breakeven",
  },

  // =================================================================== MACRO
  {
    id: "curve",
    name: "Yield curve: bootstrap, Nelson–Siegel & Svensson",
    section: "macro",
    summary: "Treasury constant-maturity yields are par yields. Bootstrapping turns them into discount factors, zero rates and forwards; Nelson–Siegel(-Svensson) describes the curve with a level, a slope and one or two humps.",
    formulas: [
      { tex: T`1 = \frac cf\sum_{k<n}P(t_k) + \left(1 + \frac cf\right)P(t_n)` },
      { tex: T`y(t) = \beta_0 + \beta_1\frac{1-e^{-t/\tau}}{t/\tau} + \beta_2\left(\frac{1-e^{-t/\tau}}{t/\tau} - e^{-t/\tau}\right)` },
    ],
    assumptions: ["Par yields are interpolated with a monotone cubic (PCHIP); bills are single-payment, bond-equivalent.", "Zero rates are continuously compounded; beyond the last node the forward is flat."],
    appears: [MACRO, MARKETS],
    refs: ["hull_ofod", "nelson_siegel_1987", "svensson_1994", "gurkaynak_2007"],
    keywords: "yield curve zero forward par treasury nss",
  },
  {
    id: "yield-pca",
    name: "Yield-curve PCA (level, slope, curvature)",
    section: "macro",
    summary: "Daily yield changes across maturities are driven mostly by three patterns: the whole curve shifting (level), steepening (slope) and the belly moving against the wings (curvature).",
    formulas: [{ tex: T`S = \frac{\Delta Y_c^\top\Delta Y_c}{T-1} = V\,\operatorname{diag}(\lambda)\,V^\top` }],
    assumptions: ["Uses dates where every chosen tenor is quoted on both days; changes in basis points.", "Loadings are signed for readability (PC1 positive sum, PC2 rising with maturity)."],
    appears: [MACRO],
    refs: ["litterman_scheinkman_1991"],
    keywords: "principal components level slope curvature",
  },
  {
    id: "bonds",
    name: "Bond analytics: yield, duration, convexity, key rates",
    section: "macro",
    summary: "Price a fixed-coupon bond from a yield or a curve, and measure how its price reacts to rates: duration (first order), convexity (second order), DV01 and key-rate durations along the curve.",
    formulas: [
      { tex: T`\text{Dirty}(y) = \sum_{k=1}^n\frac{CF_k}{(1+y/f)^{k-1+w}},\quad D^* = \frac{D}{1+y/f}` },
      { tex: T`KRD_i = \frac{P(z - \Delta z\,w_i) - P(z + \Delta z\,w_i)}{2P_0\,\Delta z}` },
    ],
    assumptions: ["US Treasury street convention with ACT/ACT accrued interest.", "Key-rate tents sum to one, so KRDs sum to effective duration."],
    appears: [MACRO],
    refs: ["fabozzi", "ho_1992"],
    keywords: "duration convexity dv01 key rate z-spread",
  },
  {
    id: "recession",
    name: "Recession probability & the Sahm rule",
    section: "macro",
    summary: "An inverted yield curve has preceded US recessions. A probit model turns today's 10-year minus 3-month spread into a probability of recession twelve months ahead; the Sahm rule flags when unemployment has risen half a point from its recent low.",
    formulas: [
      { tex: T`P(\text{REC}_{t+12} = 1) = \Phi(a + b\cdot\text{spread}_t)` },
      { tex: T`\text{SAHM}_t = \overline{u}^{(3)}_t - \min\left(\overline{u}^{(3)}_{t-12..t-1}\right) \ge 0.50` },
    ],
    assumptions: ["NBER recession dates; Newey–West standard errors with h lags because targets overlap.", "Fit quality reported as Estrella's pseudo-R²."],
    appears: [MACRO],
    refs: ["estrella_mishkin_1998", "sahm_2019", "newey_west_1987"],
    keywords: "probit inversion unemployment",
  },
  {
    id: "regimes",
    name: "Market regimes (Markov switching) & risk-on/off panel",
    section: "macro",
    summary: "Markets alternate between calm and turbulent states. A hidden Markov model estimates each state's mean and volatility and the probability of being in each today; a transparent panel scores VIX, credit spreads, curve slope and trend.",
    formulas: [{ tex: T`r_t = \mu_{S_t} + \sigma_{S_t}\varepsilon_t,\quad p_{ij} = P(S_t = j \mid S_{t-1} = i),\quad \mathbb{E}[\text{duration}_i] = \frac{1}{1-p_{ii}}` }],
    assumptions: ["Filtered probabilities are real-time; smoothed ones use the full sample.", "Panel scores use each series' own history (percentile ranks), not fixed thresholds."],
    appears: [MACRO],
    refs: ["hamilton_1989", "kim_1994", "faber_2007"],
    keywords: "hidden markov regime switching risk on off",
  },
  {
    id: "taylor",
    name: "Taylor rule",
    section: "macro",
    summary: "A benchmark for where the policy rate “should” be given inflation and the output gap, compared with the actual fed funds rate.",
    formulas: [{ tex: T`i_t = r^* + \pi_t + 0.5(\pi_t - \pi^*) + b\cdot\text{gap}_t,\quad b = 0.5\ \text{(Taylor)},\ 1.0\ \text{(balanced)}` }],
    assumptions: ["π = core PCE year-over-year; gap = real GDP vs CBO potential.", "r* and π* are user inputs (Taylor's calibration 2% / 2%), not market data."],
    appears: [MACRO],
    refs: ["taylor_1993", "yellen_2012"],
    keywords: "monetary policy fed funds",
  },

  // =================================================================== FUNDAMENTALS
  {
    id: "statements",
    name: "Standardized statements & TTM",
    section: "fundamentals",
    summary: "Company XBRL filings are mapped to one chart of accounts, with prioritized tags for items companies label differently over time. Quarters reported only year-to-date are derived as differences; trailing-twelve-month figures sum four consecutive quarters.",
    formulas: [{ tex: T`Q_4 = FY - 9M,\qquad \text{TTM} = \sum_{j=0}^{3} Q_{t-j},\qquad g_t = \frac{x_t}{x_{t-1y}} - 1` }],
    assumptions: ["Missing items stay missing — never imputed; YoY growth is blank when the base is not positive.", "Restatements: the most recently filed value for a period wins."],
    appears: [CO("statements", "Statements")],
    refs: ["sec_edgar"],
    keywords: "xbrl 10-k 10-q ttm income statement balance sheet cash flow",
  },
  {
    id: "ratios",
    name: "Financial ratios & DuPont",
    section: "fundamentals",
    summary: "Margins, returns on capital, leverage, liquidity and efficiency. Return and turnover ratios divide by the average of opening and closing balances; ROE splits into margin × turnover × leverage.",
    formulas: [
      { tex: T`ROIC = \frac{EBIT(1-t)}{\tfrac12(IC_{t-1} + IC_t)},\quad IC = \text{Debt} + \text{Equity} - \text{Cash}` },
      { tex: T`ROE = \frac{NI}{\text{Sales}}\times\frac{\text{Sales}}{\overline{TA}}\times\frac{\overline{TA}}{\overline{E}}` },
    ],
    assumptions: ["Ratios with a non-positive denominator (e.g. negative equity) are blank.", "Effective tax clipped to 0–50%."],
    appears: [CO("ratios", "Ratios")],
    refs: ["penman_2013", "koller_2020"],
    keywords: "margin roe roa roic leverage liquidity dupont",
  },
  {
    id: "piotroski",
    name: "Piotroski F-score",
    section: "fundamentals",
    summary: "Nine pass/fail signals of improving profitability, balance-sheet strength and efficiency. High scorers among cheap stocks historically outperformed low scorers.",
    formulas: [{ tex: T`F = \sum_{j=1}^{9}F_j,\ F_j\in\{0,1\}` }],
    assumptions: ["Equity issuance is proxied by the diluted share count (XBRL lacks a uniform issuance tag).", "Needs three consecutive fiscal years; the score is blank unless all nine signals are available."],
    appears: [CO("quality", "Quality scores")],
    refs: ["piotroski_2000"],
    keywords: "f-score quality value",
  },
  {
    id: "altman",
    name: "Altman Z and Z″",
    section: "fundamentals",
    summary: "Discriminant scores that separated firms that later went bankrupt from those that did not, with distress, grey and safe zones.",
    formulas: [{ tex: T`Z = 1.2X_1 + 1.4X_2 + 3.3X_3 + 0.6X_4 + 1.0X_5` }, { tex: T`Z'' = 6.56X_1 + 3.26X_2 + 6.72X_3 + 1.05X_4` }],
    assumptions: ["Z uses today's market value of equity against the latest fiscal-year balance sheet; Z″ uses book equity (non-manufacturers).", "The coefficients are the paper's estimated parameters, not market data."],
    appears: [CO("quality", "Quality scores")],
    refs: ["altman_1968", "altman_1995"],
    keywords: "bankruptcy distress z-score",
  },
  {
    id: "beneish",
    name: "Beneish M-score",
    section: "fundamentals",
    summary: "An eight-index probit model estimated on firms caught manipulating earnings. Scores above −1.78 resemble manipulators; −2.22 is a stricter screen.",
    formulas: [{ tex: T`M = -4.84 + 0.920DSRI + 0.528GMI + 0.404AQI + 0.892SGI + 0.115DEPI - 0.172SGAI + 4.679TATA - 0.327LVGI` }],
    assumptions: ["DEPI uses depreciation & amortization combined (XBRL rarely separates them).", "A statistical flag, not evidence of wrongdoing."],
    appears: [CO("quality", "Quality scores")],
    refs: ["beneish_1999"],
    keywords: "manipulation earnings quality",
  },
  {
    id: "accruals-ohlson",
    name: "Sloan accruals & Ohlson O-score",
    section: "fundamentals",
    summary: "Accruals measure how much profit is not yet cash (high accruals tend to reverse). Ohlson's logit model converts nine accounting variables into a one-year probability of bankruptcy.",
    formulas: [{ tex: T`\text{Accruals} = \frac{NI_t - CFO_t}{\tfrac12(TA_t + TA_{t-1})}` }, { tex: T`P(\text{fail}) = \frac{1}{1 + e^{-O}}` }],
    assumptions: ["Cash-flow-statement accruals (Hribar & Collins) rather than balance-sheet accruals.", "Ohlson SIZE uses assets in dollars over the prior-year GDP deflator (1968 = 100), as in the paper; FFO is proxied by CFO."],
    appears: [CO("quality", "Quality scores")],
    refs: ["sloan_1996", "hribar_collins_2002", "ohlson_1980"],
    keywords: "sloan accruals ohlson o-score bankruptcy",
  },
  {
    id: "dcf",
    name: "Two-stage FCFF DCF, WACC & CAPM beta",
    section: "fundamentals",
    summary: "Value = the present value of the cash the business will generate for all its capital providers. Cash flow grows at a rate fading from recent revenue growth to a long-run rate, is discounted at the weighted cost of capital, and ends in a growing perpetuity.",
    formulas: [
      { tex: T`FCFF = CFO + \text{Interest}(1-t) - \text{Capex}` },
      { tex: T`EV = \sum_{i=1}^N\frac{F_i}{(1+W)^i} + \frac{F_N(1+g_T)}{(W-g_T)(1+W)^N}` },
      { tex: T`W = \tfrac{E}{D+E}k_e + \tfrac{D}{D+E}k_d(1-t),\quad k_e = r_f + \beta\,ERP` },
    ],
    assumptions: ["Data-derived defaults: r_f = FRED DGS10; g_T = FRED T10YIE; β = OLS of 60 monthly excess returns vs SPY (Blume-adjusted optional); ERP = Ken French Mkt−RF full-sample mean; k_d = interest / average debt floored at r_f; tax = 3-year average effective rate.", "End-of-year discounting; equity at market value, debt at book; g_T must be below WACC.", "When the terminal value exceeds ~75% of EV the result mostly reflects perpetuity assumptions."],
    appears: [CO("dcf", "Valuation")],
    refs: ["koller_2020", "damodaran_2012", "gordon_1962", "sharpe_1964", "lintner_1965", "blume_1971", "modigliani_miller_1963"],
    keywords: "discounted cash flow wacc capm terminal value gordon valuation",
  },
  {
    id: "reverse-dcf",
    name: "Reverse DCF",
    section: "fundamentals",
    summary: "Turn the question around: what constant growth in free cash flow is today's share price already paying for? Compare that with the company's record.",
    formulas: [{ tex: T`\text{solve } g:\ \text{Equity}(g,\dots,g;\ W, g_T) = \text{Market cap}` }],
    assumptions: ["Solved with Brent's method; equity value is strictly increasing in g for positive FCFF, so the root is unique when bracketed."],
    appears: [CO("dcf", "Valuation")],
    refs: ["mauboussin_2001"],
    keywords: "implied growth expectations investing",
  },

  // =================================================================== DATA
  {
    id: "provenance",
    name: "Provenance & the no-fabrication rule",
    section: "data",
    summary: "Every dataset carries a provenance record — source, fetch time, and a synthetic flag that is always false. If no source can serve a request, the API answers 503 with the reason and the page says so; nothing is interpolated across gaps or replaced with a constant.",
    formulas: [],
    assumptions: ["A cached copy past its freshness window is served only when a refresh fails, and is labelled “stale: refresh failed”.", "Rows with a missing close are dropped; nothing is forward-filled; an intraday partial bar never enters daily history."],
    appears: [MARKETS],
    refs: [],
    keywords: "provenance cache stale 503 offline",
  },
  {
    id: "returns",
    name: "Adjusted prices & return conventions",
    section: "data",
    summary: "Returns are computed from adjusted closes so splits and dividends do not look like crashes or rallies. Returns, weights and volatilities are decimals; FRED yields stay in percent as published.",
    formulas: [{ tex: T`r_t = \frac{P^{adj}_t}{P^{adj}_{t-1}} - 1,\qquad \sigma_{ann} = \sqrt{252}\,\operatorname{sd}(r_t)` }],
    assumptions: ["Yahoo adj close is split- and dividend-adjusted; Alpaca history uses split-only OHLC with a separate all-adjusted close; Stooq has no adjusted close (stated in provenance).", "A new dividend or split that rescales history triggers a full refetch rather than an inconsistent splice."],
    appears: [TICKER, MARKETS],
    refs: [],
    keywords: "adjusted close dividends splits units",
  },
];
