"""The kernel benchmark table (docs/perf/kernels.json; rendered to kernels.md;
served at GET /api/ops/kernels). Pure: validation and rendering only -- the
router and tools/perf/bench_kernels.py do the file I/O."""

from __future__ import annotations

import math
import re
from typing import Any

from . import API

FIELDS = ("name", "python_ms", "rust_1t_ms", "rust_2t_ms", "measured_on", "sha")

#: The problem each kernel is timed on (tools/perf/bench_kernels.py builds exactly these).
SIZES: dict[str, str] = {
    "fhs_paths": "100,000 paths x 10 days, 9 assets (GJR-t fits on the fixture ETFs)",
    "copula_t_paths": "100,000 paths x 10 days, 9 fixture ETFs, nu = 6",
    "var_es_from_pnl": "1,000,000 P&L draws, alpha = 0.99",
    "stationary_bootstrap_means": "10,000 replications of SPY's fixture returns as (x, x^2), mean block 10",
    "cscv_pbo": "fixture-ETF returns x 18 trials, S = 16 (12,870 combinations)",
    "garch_nll": "one GJR-t likelihood over SPY's fixture returns",
    "garch_fit": "one GJR-t fit on the last 1,000 SPY fixture returns",
    "backtest_weights": "9 fixture ETFs, every session, monthly executions",
    "svi_fit": "one 41-point smile",
    "realized_vol_minute": "252 sessions x 390 one-minute prices",
}

_SHA = re.compile(r"^[0-9a-f]{7,40}$")


def _ms(row: dict[str, Any], key: str, nullable: bool) -> None:
    v = row[key]
    if v is None and nullable:
        return
    if isinstance(v, bool) or not isinstance(v, (int, float)) or not math.isfinite(v) or v <= 0:
        raise ValueError(f"{row['name']}: {key} must be a positive number of milliseconds; got {v!r}")


def validate_table(doc: Any) -> list[dict[str, Any]]:
    """The table's rows, each exactly ``FIELDS``; ``ValueError`` names the first defect."""
    if not isinstance(doc, dict) or not isinstance(doc.get("kernels"), list):
        raise ValueError("the table must be an object with a 'kernels' list")
    rows = doc["kernels"]
    for row in rows:
        if not isinstance(row, dict) or set(row) != set(FIELDS):
            raise ValueError(f"each row needs exactly the fields {FIELDS}; got {sorted(row) if isinstance(row, dict) else row!r}")
        if row["name"] not in API:
            raise ValueError(f"unknown kernel {row['name']!r}")
        _ms(row, "python_ms", False)
        _ms(row, "rust_1t_ms", False)
        _ms(row, "rust_2t_ms", True)
        mo = row["measured_on"]
        if not isinstance(mo, str) or not mo.strip() or "|" in mo or "\n" in mo:
            raise ValueError(f"{row['name']}: measured_on must be one line of text without '|'")
        if not isinstance(row["sha"], str) or not _SHA.match(row["sha"]):
            raise ValueError(f"{row['name']}: sha must be 7-40 lowercase hex characters")
    return rows


def _fmt(v: float | None) -> str:
    return "n/a" if v is None else f"{v:,.3f}"


def render_markdown(doc: Any) -> str:
    """docs/perf/kernels.md, byte for byte (test_kernels_bench pins the committed file to this)."""
    rows = validate_table(doc)
    lines = [
        "# Kernel benchmarks",
        "",
        "Generated from `docs/perf/kernels.json` by `python tools/perf/bench_kernels.py render`;",
        "the same rows are served at `GET /api/ops/kernels`. Do not edit this file by hand.",
        "",
        "Python is the NumPy reference (`quant/src/ohcamel_quant/kernels/reference.py`); Rust is",
        "`ohcamel_kernels` at one thread and at two (`n/a`: the kernel is single-threaded). Times",
        "are medians of repeated runs in milliseconds. Only rows measured on the droplet's CPU",
        "class speak for production.",
        "",
    ]
    if not rows:
        lines.append("No benchmark run is recorded yet.")
    else:
        lines += [
            "| kernel | size | Python ms | Rust 1T ms | Rust 2T ms | 1T speed-up | 2T / 1T | measured on | sha |",
            "|---|---|---:|---:|---:|---:|---:|---|---|",
        ]
        for r in sorted(rows, key=lambda r: (API.index(r["name"]), r["measured_on"])):
            up = f"{r['python_ms'] / r['rust_1t_ms']:.1f}x"
            par = "n/a" if r["rust_2t_ms"] is None else f"{r['rust_1t_ms'] / r['rust_2t_ms']:.2f}x"
            lines.append(
                f"| {r['name']} | {SIZES[r['name']]} | {_fmt(r['python_ms'])} | {_fmt(r['rust_1t_ms'])} | "
                f"{_fmt(r['rust_2t_ms'])} | {up} | {par} | {r['measured_on']} | {r['sha']} |"
            )
    return "\n".join(lines) + "\n"
