#!/usr/bin/env python3
"""Regenerate interface/examples/*.json and expected.json. Standard library only.

One example per rule, plus one that passes. expected.json states the core's
clock and registry, whether the schema accepts each document, and what the
core must answer. Run `alpha contract check --core ...` to hold both sides to
it. Edit THIS file, not the outputs.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
H = "sha256:" + "0" * 64

BASE = {
    "schema_version": 1,
    "strategy": "ma_crossover",
    "params_hash": H,
    "as_of": "2020-12-31",
    "computed_at": "2026-09-02T00:00:00Z",
    "data_hash": H,
    "sequence": 6,
    "validation": {"status": "pass", "gates_version": "2026-09-02", "dsr": 0.31, "psr": 0.72, "pbo": 0.2, "manifest": None},
    "targets": [{"symbol": "SPY", "weight": 1.0}],
}


def variant(**changes: object) -> dict[str, object]:
    d = json.loads(json.dumps(BASE))
    for k, v in changes.items():
        if k == "validation_status":
            d["validation"]["status"] = v
        else:
            d[k] = v
    return d


# name -> (document, schema_valid, core verdict)
CASES = {
    "pass.json": (variant(), True, "ACCEPT"),
    "r1_schema_version.json": (variant(schema_version=2), False, "REJECT R1"),
    "r2_unregistered.json": (variant(strategy="nobody"), True, "REJECT R2"),
    "r3_future.json": (variant(as_of="2021-01-04"), True, "REJECT R3"),
    "r4_stale.json": (variant(as_of="2020-12-24"), True, "REJECT R4"),
    "r4_boundary_fresh.json": (variant(as_of="2020-12-28"), True, "ACCEPT"),
    "r5_replayed.json": (variant(sequence=5), True, "REJECT R5"),
    "r6_unvalidated.json": (variant(validation_status="unvalidated"), True, "REJECT R6"),
    "r6_failed.json": (variant(validation_status="fail"), True, "REJECT R6"),
    "r7_outside_universe.json": (variant(targets=[{"symbol": "TSLA", "weight": 1.0}]), True, "REJECT R7"),
    "r7_over_levered.json": (variant(targets=[{"symbol": "SPY", "weight": 0.6}, {"symbol": "TLT", "weight": 0.6}]), False, "REJECT R7"),
    "r7_bad_weight.json": (variant(targets=[{"symbol": "SPY", "weight": 1.5}]), False, "REJECT R7"),
    "r7_short_ok.json": (variant(targets=[{"symbol": "SPY", "weight": -0.5}, {"symbol": "TLT", "weight": 0.5}]), True, "ACCEPT"),
    "order_r2_before_r6.json": (variant(strategy="nobody", validation_status="unvalidated"), True, "REJECT R2"),
}

EXPECTED = {
    "_comment": "Generated by generate.py. The clock is four real trading days present in fixtures/bars.",
    "clock": {"bar_dates": ["2020-12-28", "2020-12-29", "2020-12-30", "2020-12-31"], "max_age": 3},
    "registry": {"strategies": ["ma_crossover"], "last_sequence": {"ma_crossover": 5}},
    "universe": ["SPY", "QQQ", "IWM", "TLT", "IEF", "GLD", "XLE", "XLF", "XLK"],
    "cases": {name: {"schema_valid": ok, "core": verdict} for name, (_, ok, verdict) in CASES.items()},
}

if __name__ == "__main__":
    for name, (doc, _, _) in CASES.items():
        (HERE / name).write_text(json.dumps(doc, indent=2) + "\n")
    (HERE / "expected.json").write_text(json.dumps(EXPECTED, indent=2) + "\n")
    print(f"wrote {len(CASES)} examples and expected.json")
